### ISSUE TITLE
Falta um método getAllLocations na LocationFactory

### ISSUE THREAD

**Issue by luizribeiro** [onibuscerto/onibuscerto#1]
No algoritmo para encontrar o menor caminho, no momento estamos usando o método getAllStops. No entanto, esse método não inclui as Locations na Collection retornada. Precisamos de um método que retorne, além das Stops, as Locations. Ou um método separado para retornar apenas as Locations, não sei.

**Comment by brunoweingraber** [comment]
As Locations no caso seriam somente o inicio de fim do caminho certo? Acredito que daria pra implementar o método retornando Stops e Locations, sendo que as duas Locations que não são Stops estariam na primeira e última posições da Collection retornada.

**Comment by luizribeiro** [comment]
Poisé, percebi que o shortest path já tá fazendo algo parecido com isso que você falou... Ele inclui os Locations source e target na Collection manualmente.
Talvez nem precise disso então mesmo.

**Comment by luizribeiro** [comment]
É, nem precisa disso não.
