### ISSUE TITLE
Uso de GlobalPosition

### ISSUE THREAD

**Issue by lucascp** [onibuscerto/onibuscerto#15]
A maioria das entidades na api tem dois atributos, lat e lon, ao invés de usar GlobalPositions. Seria interessante deixar tudo com Global Position para ficar igual ao service.

**Comment by luizribeiro** [comment]
Fiz isso na versão mais recente do service. A intenção é tirar os métodos {get,set}{Latitude,Longitude} em algum momento? Ou vamos manter eles mesmo assim e passar a usar os métodos {get,set}GlobalPosition no lugar?

Eu voto na segunda opção. :P

**Comment by lucascp** [comment]
A segunda opção está boa para mim, embora se em algum ponto a gente ver que daria pouco trabalho mudar o que falta, acho que seria melhor trocar tudo. Mas não é o caso por enquanto, então podemos só adicionar métodos pra trabalhar com GlobalPosition e manter os antigos. Estou fechando essa issue então, e isso fica definido assim.
