### ISSUE TITLE
Unificar configurações do sistema

### ISSUE THREAD

**Issue by luizribeiro** [onibuscerto/onibuscerto#20]
Atualmente, temos algumas constantes de configuração definidas em vários lugares perdidos do código. Por exemplo, a constante MAX_WALKING_DISTANCE do importer ou a constante (que nem está atribuida em nenhuma variável) que determina a folga na hora de fazer uma transferência entre duas Trips, que está no ainda um tanto quanto esotérico método findShortestPath do DatabaseController.

Nós precisamos unificar estas configurações de alguma forma. Seria bom ter um arquivo de configuração no qual a gente possa setar todos estes valores, por exemplo.

Este arquivo de configuração não precisa ser, necessariamente, um arquivo lido em tempo de execução. Talvez uma classe com uma série de constantes seria o suficiente.

E aí, idéias?

**Comment by brunoweingraber** [comment]
Bom.. eu criei uma classe Constants para centralizar as constantes de configuração.
